site:
  name: "Atelier d'Ailes"
  site: 'https://www.atelier-d-ailes.fr'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: dQemWi2myMxVJEw0JkmUhb0ml3Pr202xT4n-MgWrzDA

# Default SEO metadata
metadata:
  title:
    default: "Atelier d'Ailes"
    template: "%s — Atelier d'Ailes"
  description: 'Atelier de révision et de réparation de parapentes et de matériel de vol libre, basé en Seine et Marne (77).'
  canonical: 'https://www.atelier-d-ailes.fr'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: "Atelier d'Ailes"
    images:
      - url: '~/assets/images/logo-with-white-background.png'
        width: 1200
        height: 628
    type: website
  keywords:
    - parapente
    - révision parapente
    - réparation parapente
    - vol libre
    - atelier parapente
    - Seine-et-Marne
    - Ile-de-France
    - paramoteur

i18n:
  language: fr
  textDirection: ltr

analytics:
  vendors:
    googleAnalytics:
      id: null # or "G-XXXXXXXXXX"

ui:
  theme: 'light' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
